# -*- coding: utf-8 -*-
"""Cogcomcelvenorrectposeall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kghUmPkabcb4f-ohYJHAJuJp_OA6qlHW
"""

# ---------------------------
# INSTALL (Colab / Jupyter)
# ---------------------------
!pip install ultralytics opencv-python numpy -q

import cv2
import numpy as np
import math
import json
from ultralytics import YOLO

# ---------------------------
# CONFIG
# ---------------------------
INPUT_VIDEO = "video.mp4"
OUTPUT_VIDEO = "inference_video.mp4"
OUTPUT_JSON = "timeline.json"
MODEL_PATH = "yolo11n-pose.pt"
MIN_CONF = 0.25

# COCO keypoint indices
KP = {
    "nose": 0, "l_eye": 1, "r_eye": 2, "l_ear": 3, "r_ear": 4,
    "l_sh": 5, "r_sh": 6, "l_el": 7, "r_el": 8, "l_wr": 9, "r_wr": 10,
    "l_hp": 11, "r_hp": 12, "l_kn": 13, "r_kn": 14, "l_an": 15, "r_an": 16
}

# Skeleton connections for COCO-17 pose
SKELETON = [
    (5, 6), (5, 7), (7, 9), (6, 8), (8, 10),
    (5, 11), (6, 12), (11, 12), (11, 13), (13, 15),
    (12, 14), (14, 16)
]

# ---------------------------
# MATH HELPERS
# ---------------------------
class Vec:
    @staticmethod
    def unit(v):
        v = np.asarray(v, dtype=np.float32)
        n = np.linalg.norm(v)
        return v / n if n > 1e-6 else np.zeros_like(v)

    @staticmethod
    def perp(v):
        v = np.asarray(v, dtype=np.float32)
        return np.array([-v[1], v[0]], dtype=np.float32)

    @staticmethod
    def angle(a, b, c):
        a = np.asarray(a, dtype=np.float32)
        b = np.asarray(b, dtype=np.float32)
        c = np.asarray(c, dtype=np.float32)
        ba = Vec.unit(a - b)
        bc = Vec.unit(c - b)
        return float(np.degrees(np.arccos(np.clip(np.dot(ba, bc), -1.0, 1.0))))

# ---------------------------
# DRAW HELPERS
# ---------------------------
class Drawer:
    def point(self, frame, p, color=(0, 255, 255), r=4):
        if p is None:
            return
        cv2.circle(frame, tuple(np.round(p).astype(int)), r, color, -1)

    def line(self, frame, p1, p2, color=(200, 200, 200), thickness=2):
        if p1 is None or p2 is None:
            return
        cv2.line(frame, tuple(np.round(p1).astype(int)), tuple(np.round(p2).astype(int)), color, thickness)

    def arrow(self, frame, p, v, color=(255, 0, 0), txt=None, scale=1.0):
        if p is None or v is None:
            return
        p = np.asarray(p, dtype=np.float32)
        v = np.asarray(v, dtype=np.float32) * float(scale)
        end = p + v
        cv2.arrowedLine(
            frame,
            tuple(np.round(p).astype(int)),
            tuple(np.round(end).astype(int)),
            color,
            3,
            tipLength=0.3
        )
        if txt is not None:
            cv2.putText(
                frame,
                txt,
                tuple(np.round(end).astype(int)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                color,
                1,
                cv2.LINE_AA
            )

    def arc(self, frame, a, b, c, color=(0, 255, 255)):
        if a is None or b is None or c is None:
            return
        ang1 = math.atan2(a[1] - b[1], a[0] - b[0])
        ang2 = math.atan2(c[1] - b[1], c[0] - b[0])
        diff = (ang2 - ang1 + math.pi) % (2 * math.pi) - math.pi

        pts = []
        for t in np.linspace(0, 1, 20):
            ang = ang1 + diff * t
            x = int(b[0] + 30 * math.cos(ang))
            y = int(b[1] + 30 * math.sin(ang))
            pts.append([x, y])

        pts = np.array(pts, np.int32).reshape(-1, 1, 2)
        cv2.polylines(frame, [pts], False, color, 2)

# ---------------------------
# FORCE / BALANCE / STABILITY
# ---------------------------
class Force:
    def compute(self, knee, ankle, hip, com):
        knee = np.asarray(knee, dtype=np.float32)
        ankle = np.asarray(ankle, dtype=np.float32)
        hip = np.asarray(hip, dtype=np.float32)
        com = np.asarray(com, dtype=np.float32)

        shank = ankle - knee
        normal = Vec.perp(Vec.unit(shank))
        knee_angle = Vec.angle(hip, knee, ankle)
        kf = np.cos(np.radians(knee_angle))

        offset = Vec.unit(com - ankle)
        of = float(np.dot(offset, normal))

        mag = 100 + 120 * abs(kf) + 80 * abs(of)
        vertical = np.array([0, -1], dtype=np.float32)
        direction = Vec.unit(0.6 * normal + 0.4 * vertical)
        return direction * mag, float(mag)

class Stability:
    def compute(self, com, la, ra, width):
        if com is None or (la is None and ra is None):
            return False, 0.0, None

        feet = [p for p in (la, ra) if p is not None]
        xs = [float(p[0]) for p in feet]
        xmin, xmax = min(xs), max(xs)

        # Expand support region a bit
        margin = 0.12 * width
        xmin -= margin
        xmax += margin

        dist = 0.0
        if com[0] < xmin:
            dist = xmin - com[0]
        elif com[0] > xmax:
            dist = com[0] - xmax

        score = float(np.exp(-dist / 40.0))
        stable = score > 0.5

        support_center = np.array([(xmin + xmax) / 2.0, float(np.mean([la[1], ra[1]]) if la is not None and ra is not None else feet[0][1])], dtype=np.float32)
        return stable, score, support_center

# ---------------------------
# MAIN ENGINE
# ---------------------------
class Engine:
    def __init__(self):
        self.model = YOLO(MODEL_PATH)
        self.draw = Drawer()
        self.force = Force()
        self.stab = Stability()

    def _get(self, kpts, conf, i):
        return kpts[i] if conf[i] > MIN_CONF else None

    def process_person(self, frame, kpts, conf, person_id):
        def get(i):
            return self._get(kpts, conf, i)

        # Draw skeleton
        for a, b in SKELETON:
            if conf[a] > MIN_CONF and conf[b] > MIN_CONF:
                self.draw.line(frame, kpts[a], kpts[b])

        # Draw keypoints
        for i in range(len(kpts)):
            if conf[i] > MIN_CONF:
                self.draw.point(frame, kpts[i])

        # Joint angles
        joints = [
            (KP["l_sh"], KP["l_el"], KP["l_wr"]),
            (KP["r_sh"], KP["r_el"], KP["r_wr"]),
            (KP["l_hp"], KP["l_kn"], KP["l_an"]),
            (KP["r_hp"], KP["r_kn"], KP["r_an"])
        ]

        angles = {}
        for a, b, c in joints:
            key = f"{a}_{b}_{c}"
            if conf[a] > MIN_CONF and conf[b] > MIN_CONF and conf[c] > MIN_CONF:
                ang = Vec.angle(kpts[a], kpts[b], kpts[c])
                angles[key] = ang
                self.draw.arc(frame, kpts[a], kpts[b], kpts[c])
                cv2.putText(
                    frame,
                    f"{int(round(ang))}°",
                    tuple(np.round(kpts[b]).astype(int)),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.5,
                    (255, 255, 255),
                    1,
                    cv2.LINE_AA
                )

        # COM / CoG approximation from hips + knees if available
        pts = []
        for key in ("l_hp", "r_hp", "l_kn", "r_kn"):
            p = get(KP[key])
            if p is not None:
                pts.append(p)

        com = np.mean(pts, axis=0) if len(pts) else None
        cog = com  # same approximation here

        if com is not None:
            com_xy = tuple(np.round(com).astype(int))
            cv2.circle(frame, com_xy, 6, (255, 0, 255), -1)
            cv2.putText(
                frame,
                f"COM/CoG {person_id}",
                com_xy,
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                (255, 0, 255),
                1,
                cv2.LINE_AA
            )

        la = get(KP["l_an"])
        ra = get(KP["r_an"])

        # Support line between ankles
        if la is not None and ra is not None:
            self.draw.line(frame, la, ra, (0, 200, 255), 2)

        left_force = None
        right_force = None
        balance_vector = None
        support_center = None

        # Left leg force vector
        if get(KP["l_kn"]) is not None and la is not None and get(KP["l_hp"]) is not None and com is not None:
            v, m = self.force.compute(get(KP["l_kn"]), la, get(KP["l_hp"]), com)
            self.draw.arrow(frame, la, v, (255, 0, 0), f"{int(round(m))}", scale=0.15)
            left_force = {"vector": [float(v[0]), float(v[1])], "mag": float(m)}

        # Right leg force vector
        if get(KP["r_kn"]) is not None and ra is not None and get(KP["r_hp"]) is not None and com is not None:
            v, m = self.force.compute(get(KP["r_kn"]), ra, get(KP["r_hp"]), com)
            self.draw.arrow(frame, ra, v, (255, 0, 0), f"{int(round(m))}", scale=0.15)
            right_force = {"vector": [float(v[0]), float(v[1])], "mag": float(m)}

        # Stability
        stable, score, support_center = self.stab.compute(com, la, ra, frame.shape[1])

        # Balance vector: from COM to support center
        if com is not None and support_center is not None:
            balance_vector = support_center - com
            self.draw.arrow(frame, com, balance_vector, (0, 255, 0) if stable else (0, 0, 255), "Balance", scale=1.0)

        # Stability label on video
        label = "STABLE" if stable else "UNSTABLE"
        label_color = (0, 255, 0) if stable else (0, 0, 255)

        label_pos = (30, 40 + 28 * person_id)
        if com is not None:
            label_pos = tuple(np.round(com + np.array([10, -10], dtype=np.float32)).astype(int))

        cv2.putText(
            frame,
            f"{label} ({score:.2f})",
            label_pos,
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            label_color,
            2,
            cv2.LINE_AA
        )

        return {
            "person_id": int(person_id),
            "com": [float(com[0]), float(com[1])] if com is not None else None,
            "cog": [float(cog[0]), float(cog[1])] if cog is not None else None,
            "support_center": [float(support_center[0]), float(support_center[1])] if support_center is not None else None,
            "left_ankle": [float(la[0]), float(la[1])] if la is not None else None,
            "right_ankle": [float(ra[0]), float(ra[1])] if ra is not None else None,
            "left_force": left_force,
            "right_force": right_force,
            "balance_vector": [float(balance_vector[0]), float(balance_vector[1])] if balance_vector is not None else None,
            "stability": {"stable": bool(stable), "score": float(score)},
            "angles": angles
        }

    def process_frame(self, frame):
        results = self.model(frame, verbose=False)

        frame_records = []
        if not results or len(results) == 0 or results[0].keypoints is None:
            cv2.putText(
                frame,
                "No person detected",
                (30, 40),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (0, 0, 255),
                2,
                cv2.LINE_AA
            )
            return frame, frame_records

        r = results[0]

        # Multi-person pose:
        # keypoints.xy -> (N, 17, 2)
        # keypoints.conf -> (N, 17)
        kpts_all = r.keypoints.xy.cpu().numpy()
        conf_all = r.keypoints.conf.cpu().numpy()

        if len(kpts_all) == 0:
            cv2.putText(
                frame,
                "No person detected",
                (30, 40),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (0, 0, 255),
                2,
                cv2.LINE_AA
            )
            return frame, frame_records

        for pid, (kpts, conf) in enumerate(zip(kpts_all, conf_all)):
            record = self.process_person(frame, kpts, conf, pid)
            frame_records.append(record)

            # Person label at nose if available, otherwise first valid point
            if conf[KP["nose"]] > MIN_CONF:
                name_xy = tuple(np.round(kpts[KP["nose"]]).astype(int))
            else:
                valid = kpts[conf > MIN_CONF]
                if len(valid) > 0:
                    name_xy = tuple(np.round(valid[0]).astype(int))
                else:
                    name_xy = (30, 80 + 25 * pid)

            cv2.putText(
                frame,
                f"Person {pid}",
                name_xy,
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                (0, 255, 255),
                2,
                cv2.LINE_AA
            )

        return frame, frame_records

# ---------------------------
# RUN
# ---------------------------
cap = cv2.VideoCapture(INPUT_VIDEO)
if not cap.isOpened():
    raise FileNotFoundError(f"Could not open input video: {INPUT_VIDEO}")

w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)
if fps is None or fps <= 1e-6:
    fps = 30.0

out = cv2.VideoWriter(
    OUTPUT_VIDEO,
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (w, h)
)

engine = Engine()
timeline = []
frame_idx = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    annotated, people = engine.process_frame(frame)
    out.write(annotated)

    timeline.append({
        "frame": int(frame_idx),
        "time": round(frame_idx / fps, 4),
        "num_persons": int(len(people)),
        "persons": people
    })

    frame_idx += 1

cap.release()
out.release()

with open(OUTPUT_JSON, "w") as f:
    json.dump(timeline, f, indent=2)

print(f"Done. Saved video: {OUTPUT_VIDEO}")
print(f"Done. Saved JSON: {OUTPUT_JSON}")